/**
 * Development is a collection of Polygons and VoxelArrays, 
 * usually generated by FuzzyBuilder.build(SettingGroup) or 
 * FuzzyRandom.development()
 *
 * @author Ira Winder
 *
 */
class Development {
  public ArrayList<Polygon> plotShapes;
  public HashMap<Polygon, ArrayList<Polygon>> towerShapes;
  public VoxelArray site, massing;
  
  public Development() {
    this.plotShapes = new ArrayList<Polygon>();
    this.towerShapes = new HashMap<Polygon, ArrayList<Polygon>>();
    this.site = new VoxelArray();
    this.massing = new VoxelArray();
  }
}
